import type { Metadata } from "next";
import { Geist, Geist_Mono, Saira_Stencil_One } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sairaStencilOne = Saira_Stencil_One({
  weight: "400",
  variable: "--font-saira-stencil-one",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${sairaStencilOne.variable} antialiased bg-[#030014] overflow-x-hidden`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
